engines:
  structure:
    enabled: true
    channel: java
  duplication:
    enabled: true
    channel: java
exclude_paths:
  - "**.js"
  - "**.jsx"
  - "**.rb"
  - "**.py"
ratings:
  paths:
    - "**.java"
